### ISSUE TITLE
Plumber crest count no longer showing on Baganator with v 0.132

### ISSUE THREAD

**Issue by Sythr4l** [Peterodox/Plumber#1]
Since the latest version of baganator, the plumber crest count feature does not appear on the baganator UI.  there are no LUA errors associated with this bug.

**Comment by lnevo** [comment]
The author suggested anchoring against. Hope this helps. Broken again with Baganator-171-2-gd759ddd.zip

`Baganator_BackpackViewFrame.Currency3`

**Comment by Peterodox** [comment]
It's been fixed in our update v1.2.5.
Baganator is being actively developed so I'll leave this ticket open in case the issue comes back.

**Comment by lnevo** [comment]
Confirmed working. Thanks for monitoring the compatibility. Two great addons :)

**Comment by zeenk** [comment]
Broken again in https://www.curseforge.com/wow/addons/baganator/files/5364983

**Comment by lnevo** [comment]
Looks like Baganator_BackpackViewFrame was renamed to Baganator_SingleViewBackpackViewFrame in that version. I changed the instances in Modules/BackpackItemTracker.lua to match and it's working again.

**Comment by Fernissx** [comment]
The crest count feature isn't showing in the Baganator addon when the bags are sorted using category.

**Comment by Fernissx** [comment]
Would the author be able to add support for the Baganator category view?

**Comment by Peterodox** [comment]
> Would the author be able to add support for the Baganator category view?

It should be working now :)

**Comment by Fernissx** [comment]
Awesome. Thank you!!

**Comment by zeenk** [comment]
https://www.curseforge.com/wow/addons/baganator/files/5747265 (retail version)

In the latest alpha version of Baganator he added a new currency ui + button in the bottom left so it's now causing some overlap issues with plumber bag tracker
## Single bag view
![2024-09-22_21-19-58](https://github.com/user-attachments/assets/b9a9f542-8590-459e-9920-e0d81b1e2fb3)
## Category view
![2024-09-22_21-20-23](https://github.com/user-attachments/assets/9e98e86d-45ef-4088-9295-80de9bb54372)

**Comment by Peterodox** [comment]
Hey everyone.
Since Baganator already has its own currency tracker, it's advised that you turn off this module in Plumber.

**Comment by lnevo** [comment]
Will try.... Plumber's view with all crests/caps and flightstone view is so perfect :)

**Comment by lnevo** [comment]
Ok... if you're referring to the traditional "Add to Backpack" currency. Baganator view on crests has nothing on what Plumber is providing. Maybe I'm missing a setting... having all crests and flightstones in one tooltip is top notch.

**Comment by lnevo** [comment]
Ok sorry for the spam. Found the feature. Flightstones aren't displayed there at all, and you have to look at everything. Definitely not the same thing.

**Comment by zeenk** [comment]
@lnevo Fixed now in latest Plumber update
