### ISSUE TITLE
"Loot all" when in combat

### ISSUE THREAD

**Issue by Alfheimen** [Peterodox/Plumber#21]
Currently "loot all" when in combat will cause you to cast whatever spell is bound to that button instead. Maybe add an option for the loot window to take priority?

**Comment by Peterodox** [comment]
Due to WoW's restrictions in combat, we can't selectively propagate or consume a key press. The alternative for this case is the game will not respond to any key other E (the current default hotkey), meaning you won't be able to move with WASD or cast any spell until the loot window is closed.

**Comment by Alfheimen** [comment]
I see, that sucks, as this means you can't really rely on it as your primary way of looting; you don't always immediately drop combat after a fight ends (it can linger for a second), meaning you can easily try to loot too fast and end up just closing the window instead. Also, you can't efficiently loot mid-combat, which is particularly annoying if you're doing some sort of group farm, or if you're unlucky enough to aggro a mob while e.g. mining.

Guess it's best to just keep auto loot on, and use "Loot all" as a backup.

**Comment by Peterodox** [comment]
You can now change the hotkey for Take All. If you bind it to a modifier key (SHIFT/ALT/CTRL), you won't worry about casting the spell bound to that key. It's unconventional but it's the only solution due to game restrictions.

**Comment by Peterodox** [comment]
You can now change the hotkey for Take All. If you bind it to a modifier key (SHIFT/ALT/CTRL), you won't worry about casting the spell bound to that key. It's unconventional but it's the only solution due to game restrictions.
