### ISSUE TITLE
Plumber/Locales/frFR.lua:1 Plumber/Locales/frFR.lua:233: unfinished string

### ISSUE THREAD

**Issue by Sluimerstand** [Peterodox/Plumber#29]
```
4x Plumber/Locales/frFR.lua:1 Plumber/Locales/frFR.lua:233: unfinished string near '"Utiliser la fenêtre de butin par défaut de WoW.

Activer cette option annule tous les réglage'
```

It's on the CurseForge comments as well, but I figured a ticket might get your attention faster. o7

Edit: I see Molkree already placed in a pull request with the fix, ticket wasn't really needed, apologies.

**Comment by Aryksa** [comment]
If I may, there is also a mistake, it should be "tout les réglage**S**" ^^'
