### ISSUE TITLE
Crests not showing in BetterBags

### ISSUE THREAD

**Issue by karaktaka** [Peterodox/Plumber#3]
BetterBags is the successor of AdiBags, but unfortunately the Crests are not being shown in BetterBags anymore.

Possibly as BetterBags is using a different kind of showing the Currencies.

**Comment by Peterodox** [comment]
Not sure what caused it. [BetterBags v0.1.9](https://legacy.curseforge.com/wow/addons/better-bags/files/5139120) works fine on my end :(
![BBs](https://github.com/Peterodox/Plumber/assets/49627468/eee52402-fa58-4ddf-b8c4-655350043a0b)

**Comment by karaktaka** [comment]
For me it is still not showing with 0.1.9 of BetterBags
![grafik](https://github.com/Peterodox/Plumber/assets/1451140/c9a7eb36-ca7d-49db-bf8d-33f6c244b8ca)

**Comment by Peterodox** [comment]
Are you using any other reskin add-ons or other BetterBags modules? For some reason, I can't track more than one currency on the BetterBags UI and I've disabled every other add-on. And when I track a different currency the BetterBags UI doesn't update until /reload.

**Comment by karaktaka** [comment]
So, I tried today with disabled addons and as soon as I enable elvui again the crest display is gone. Which is weird as I was using plumber with elvui before but with adibags and it showed just fine.

**Comment by Peterodox** [comment]
Thanks for the response!
Plumber searches for compatible addons during the initial loading process. When it finds ElvUI it will assume you're using ElvUI bag and move the BackpackItemTracker there. I will move ElvUI to the bottom of the search list so it will prioritize other bag-dedicated addons.

**Comment by karaktaka** [comment]
Hey, I can confirm this working again. Thank you for the fix. :)
