### ISSUE TITLE
[Suggestion] Option for class colors in all dropdowns on Retail

### ISSUE THREAD

**Issue by zeenk** [Peterodox/Plumber#32]
This is not really a big deal but since this is a quality of life addon I thought that this could be a nice addition to this addon, but if you think this is unnecessary/doesn't fit the addon feel free to close this request ^^

Basically what I'm suggesting is to add class colors to all the dropdown menus in the game on Retail, I just don't how many class dropdowns there is or if there is a way to apply them everywhere without having to do it on each frame that has them 😛 

There might be more locations but these are some that I know of that uses class dropdowns:
Heirloom tab (shift +p)
Appearances, both in items & sets tab (shift+p)
Dungeon/Raids/Item Sets tabs (shift+j)

## Current
![2024-10-19_02-24-15](https://github.com/user-attachments/assets/3adc0b61-2396-4a12-80d2-f6b6867d6311)
![2024-10-19_02-34-22](https://github.com/user-attachments/assets/7a30db43-3ee3-464b-a0e0-6e3f32396130)

## Suggestion
![2024-10-19_02-24-15s](https://github.com/user-attachments/assets/ab332bda-5103-4b40-a5e8-ce0f68b38869)
![2024-10-19_02-24-01](https://github.com/user-attachments/assets/c99c4310-5fe2-4783-9854-8c2f020ec502)

**Comment by Peterodox** [comment]
Hi!
I'd like that but as far as I know, it's difficult to modify buttons on a menu like this. Adding new buttons is easy, but changing existing ones is not.

**Comment by zeenk** [comment]
Aw oki, I know that this addon has this feature but only for the appearance tab and didn't want all the extra stuff from it 😛 https://github.com/teelolws/MplusAG/commit/25e42be17b5e2372f9ca4ac97ac4f44f793cb71d
