### ISSUE TITLE
[Bug] Action Bar positions being reset to default if overlapping Loot Window component

### ISSUE THREAD

**Issue by F-Lambda** [Peterodox/Plumber#33]
Seems Blizz changed something with how Action Bars are allowed to overlap with other UI elements in 11.0.5. So if you have the loot window component overlapping an action bar you've added, such as action bars 6 or 7, then they'll reset to their default position in the upper left-hand corner.

Here's an example bar setup that causes it; the Loot window is in the bottom right hand corner, and Action Bar 6 gets reset. Action Bar 7 also gets reset, presumably because it overlaps the minimap:
![image](https://github.com/user-attachments/assets/b96ec0cd-44fa-4ac6-9670-f74f37065444)

**Comment by F-Lambda** [comment]
Okay this is weird as hell, seems opening Edit Mode then closing it without making any changes puts them back in their correct position?!?!

**Comment by Peterodox** [comment]
Hi!
It's likely a Blizzard issue. [https://us.forums.blizzard.com/en/wow/t/bug-6th-action-bar-position-resetting/1991191](url)

**Comment by Peterodox** [comment]
Try duplicating your current layout and deleting the old one.
https://us.forums.blizzard.com/en/wow/t/ui-bugged-everytime-i-log-in-with-or-without-addons-started-on-patch/1991257
