### ISSUE TITLE
Anniversary Fashion event causing error - WoWAnniversary.lua:635: attempt to call method 'Release' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [Peterodox/Plumber#34]
During the fashion show the following error kept occurring. Running 1.4.5c. Thanks.

38x Plumber/Modules/WoWAnniversary.lua:635: attempt to call method 'Release' (a nil value)
[string "@Plumber/Modules/WoWAnniversary.lua"]:635: in function `Layout'
[string "@Plumber/Modules/WoWAnniversary.lua"]:586: in function `UpdateEntries'
[string "@Plumber/Modules/WoWAnniversary.lua"]:570: in function <Plumber/Modules/WoWAnniversary.lua:565>

Locals:
self = Frame {
 Divider = Texture {
 }
 guidData = <table> {
 }
 n = 11
 pieces = <table> {
 }
 guidButton = <table> {
 }
 baseTime = 1729649913
 ExpandCollapseButton = Button {
 }
 numSlices = 9
 expanded = true
 entryButtonPool = <table> {
 }
 entries = <table> {
 }
 Highlight = Texture {
 }
 Title = FontString {
 }
 playerGUID = "Player-1168-0699720B"
}
playerFound = true
button = Frame {
 fullName = "Dädlife-Ner'zhul"
 characterName = "Dädlife-Ner'zhul"
 isPlayer = false
 Name = FontString {
 }
 used = true
 Count = FontString {
 }
}
numButtons = 10
fromOffset = 36
(for state) = <table> {
 Player-1168-09ABF3A0 = Frame {
 }
 Player-1168-0ACCE74C = Frame {
 }
 Player-1168-0699720B = Frame {
 }
 Player-1168-09DC539E = Frame {
 }
 Player-1168-0ACC3F29 = Frame {
 }
 Player-1168-067397DF = Frame {
 }
 Player-1168-09DB5B22 = Frame {
 }
 Player-1168-094961E2 = Frame {
 }
 Player-73-0E85AE6E = Frame {
 }
 Player-1168-0A4FEA30 = Frame {
 }
 Player-1168-0AB11D6A = Frame {
 }
}
(for control) = "Player-73-0E85AE6E"
_ = "Player-73-0E85AE6E"
button = Frame {
 fullName = "Grylka-BleedingHollow"
 characterName = "Grylka-BleedingHollow"
 isPlayer = false
 Name = FontString {
 }
 used = false
 Count = FontString {
 }
}
(*temporary) = nil
(*temporary) = Frame {
 fullName = "Grylka-BleedingHollow"
 characterName = "Grylka-BleedingHollow"
 isPlayer = false
 Name = FontString {
 }
 used = false
 Count = FontString {
 }
}
(*temporary) = "attempt to call method 'Release' (a nil value)"
PADDING_V = 6
BUTTON_HEIGHT = 24
MAX_ENTRY_PER_PAGE = 10

**Comment by Peterodox** [comment]
Thanks for the report.
Hopefully, our latest update will fix it 🥹
