### ISSUE TITLE
[Minor bug] Merchant Price's currency display does not include reagent bank or Warband bank

### ISSUE THREAD

**Issue by Sluimerstand** [Peterodox/Plumber#37]
The currency display from the Merchant Price setting is great (as are most features, and the entire addon), but it does not include items held in the bank, reagent bank, or the Warband bank.

![image](https://github.com/user-attachments/assets/b573b9b8-e71b-4580-aeed-5352143f6f14)

Items held there can be used for purchasing items from vendors, and Plumber does appropriately color the vendor's item's costs as having enough in cases where the player has enough in total, but not directly in their bags.

![image](https://github.com/user-attachments/assets/5942978a-754a-4ec4-afcb-d181a46ce296)

I assume this would be a simple fix by setting the optional parameters for `C_Item.GetItemCount` to `true, false, true, true`.

**Comment by Peterodox** [comment]
Hi and thank you!
I'll include banks in the next update.
This was intentional because I was concerned about the game's inconsistency regarding whether or not you could consume bank items directly. For example, Crafting Orders didn't consider Warband Bank until 11.0.5.
