### ISSUE TITLE
Handy Lockpick overwrites default tooltip on lockboxes

### ISSUE THREAD

**Issue by Xarano-GIT** [Peterodox/Plumber#39]
When Handy Tooltip is enabled, the tooltip for lockboxes is overwritten, which disallows other addons to write information into the tooltip.

I use addons such as Syndicator, which will count how many lockboxes I have in my inventory, bank etc, but I cannot see this info when Handy Lockpick is enabled.

**Comment by Peterodox** [comment]
I just changed method to display bag item tooltip. You should be able to see content added by other addons now.

**Comment by Xarano-GIT** [comment]
Works Perfectly, thanks!

https://github.com/user-attachments/assets/938ec46f-661b-4d94-9dc7-173530e11718

**Comment by Peterodox** [comment]
Wonderful!
Case closed.
