### ISSUE TITLE
1.4.8 Lua Error, cannot move mount mania button.

### ISSUE THREAD

**Issue by Eremeir** [Peterodox/Plumber#40]
[Err.txt](https://github.com/user-attachments/files/17667422/Err.txt)

Cannot reposition mount mania quickmount by any method, whether the change position option is clicked or not.

**Comment by Hyphie24** [comment]
looks to be a Y value missing in the code, hopefully will be an easy fix

Also, possible to add a setting to allow moveable when not in mount mania, would like to be able to position it when event is not currently running

**Comment by Peterodox** [comment]
Thanks for the report!
It's been fixed in the latest update v1.4.8-b.
