### ISSUE TITLE
Lockpicking.lua error

### ISSUE THREAD

**Issue by formigao** [Peterodox/Plumber#42]
16x Plumber/Modules/Lockpicking.lua:467: attempt to call method 'unregisterEvent' (a nil value)
[string "@Plumber/Modules/Lockpicking.lua"]:467: in function `toggleFunc'
[string "@Plumber/ControlCenter.lua"]:575: in function `InitializeModules'
[string "@Plumber/ControlCenter.lua"]:621: in function <Plumber/ControlCenter.lua:618>

Locals:
state = false
(*temporary) = nil
(*temporary) = Frame {
}
(*temporary) = "BANKFRAME_OPENED"
(*temporary) = "attempt to call method 'unregisterEvent' (a nil value)"
MODULE_ENABLED = false
TooltipFrame = nil
Processor = Frame {
}

**Comment by Peterodox** [comment]
Thanks for the report.
It's been fixed in our latest update.
