### ISSUE TITLE
TalkingHead Error - Retial

### ISSUE THREAD

**Issue by LarryThiessen** [Peterodox/Plumber#5]
3x Plumber/Modules/TalkingHead.lua:347: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback, voiceOverPriorityID]
[string "=[C]"]: ?
[string "@Plumber/Modules/TalkingHead.lua"]:347: in function `OnTalkingHeadRequested'
[string "@Plumber/Modules/TalkingHead.lua"]:407: in function <Plumber/Modules/TalkingHead.lua:403>

Locals:
(*temporary) = nil
(*temporary) = "Talking Head"
(*temporary) = true
(*temporary) = true

**Comment by Peterodox** [comment]
I should be fixed now :)
